export const CARDS_ARE_FETCHING = "CARDS_ARE_FETCHING";
export const CARDS_FETCH_DATA_SUCCESS = "CARDS_FETCH_DATA_SUCCESS";
export const CARDS_FETCH_DATA_ERRORED = "CARDS_FETCH_DATA_ERRORED";
export const CARDS_FETCH_DATA_INFINTE_SCROLLING = "CARDS_FETCH_DATA_INFINTE_SCROLLING";